mongodb-js/devtools-shared

- .github/workflows/check-test.yaml
- .github/workflows/publish.yaml
> chore: run tests before publish

- .github/workflows/publish.yaml
> chore(ci): fix lerna command

- .github/workflows/publish.yaml
> chore: assume-unchanged npmrc

- .github/workflows/publish.yaml
> chore(ci): bootstrap before publish

- .github/workflows/bump-packages.yaml
- .github/workflows/check-test.yaml
- .github/workflows/publish-packages.yaml
- package-lock.json
- package.json
- scripts/bump-packages/README.md
- scripts/bump-packages/bump-packages.js
- scripts/bump-packages/bump-packages.spec.js
- scripts/bump-packages/fixtures/bump-package-1-breaking.json
- scripts/bump-packages/fixtures/bump-package-1-feat.json
- scripts/bump-packages/fixtures/bump-package-without-deps.json
- scripts/bump-packages/fixtures/last-commit-is-bump.json
- scripts/bump-packages/fixtures/no-bump-commit.json
- scripts/bump-packages/get-conventional-bump.js
- scripts/bump-packages/get-conventional-bump.spec.js
- scripts/bump-packages/max-increment.js
- scripts/bump-packages/max-increment.spec.js
- scripts/package.json
- Fix and tests and document the package bump task
- Enable tests on main
> chore: fix package bump

- .github/workflows/publish-packages.yaml
> chore(ci): publish packages with workflow_dispatch

- .github/workflows/publish-packages.yaml
> chore(ci): fix if on publish and allow workflow_dispatch

- .github/workflows/publish-packages.yaml
> chore(ci): fix jq expr that lists tags

- configs/eslint-config-devtools/package.json
- packages/bump-monorepo-packages/package.json
- packages/get-os-info/package.json
- scripts/package.json
- scripts/src/create-workspace.js
> chore: fix repository fields in package.json

- packages/mongodb-constants/src/stage-operators.ts
[COMPASS-6489](https://jira.mongodb.org/browse/COMPASS-6489)
---
> fix(mongodb-constants): adds missing database aggregation stages

- package-lock.json
- packages/oidc-mock-provider/.depcheckrc
- packages/oidc-mock-provider/.eslintignore
- packages/oidc-mock-provider/.eslintrc.js
- packages/oidc-mock-provider/.mocharc.js
- packages/oidc-mock-provider/.prettierignore
- packages/oidc-mock-provider/.prettierrc.json
- packages/oidc-mock-provider/LICENSE
- packages/oidc-mock-provider/package.json
- packages/oidc-mock-provider/src/index.spec.ts
- packages/oidc-mock-provider/src/index.ts
- packages/oidc-mock-provider/tsconfig-lint.json
- packages/oidc-mock-provider/tsconfig.json
For use in the tests of Compass, mongosh, and the OIDC plugin.
> feat: add oidc-mock-provider package MONGOSH-1382

- packages/oidc-mock-provider/README.md
> feat: dummy PR to force oidc-mock-provider publish

- packages/mongodb-constants/src/accumulators.ts
Add `$percentile` and its special case, a `$median`, to shared constants.
> feat: add autocomplete support for $percentile and $median accumulators COMPASS-6781

- packages/oidc-mock-provider/src/index.ts
> feat(oidc-mock-provider): allow overriding behavior for specific request types

- packages/oidc-mock-provider/src/index.ts
> fix(oidc-mock-provider): relax override callback signature

- .github/workflows/bump-packages.yaml
- .github/workflows/check-test.yaml
- .github/workflows/publish-packages.yaml
> chore: bump node and npm in CI

- scripts/package.json
oops https://github.com/mongodb-js/devtools-shared/actions/runs/5356531768/jobs/9716165426#step:7:318
> set @mongodb-js/devtools-scripts to public so we can publish it

- package-lock.json
- package.json
- packages/monorepo-tools/package.json
I keep forgetting this sort of thing and it is hard to test without first publishing because it doesn't break when you npm link..
> publish all the code so that the bin scripts work outside of this repo

- .github/workflows/bump-packages.yaml
- .github/workflows/check-test.yaml
- .github/workflows/publish-packages.yaml
Fixup after https://github.com/mongodb-js/devtools-shared/pull/109
> fix(ci): always bootstrap monorepo-tools repo first in CI

- package-lock.json
- packages/mongodb-runner/package.json
> fix(mongodb-runner): use previous package name

- configs/eslint-config-devtools/package.json
- package-lock.json
Not sure what this was still doing there.
> chore(eslint-config-devtools): remove eslint-plugin-compass

- packages/mongodb-runner/src/cli.ts
See: https://github.com/yargs/yargs/blob/e517318cea0087b813f5de414b3cdec7b70efe33/docs/api.md#envprefix
> feat(mongodb-runner): use yargs .env() to make env var passing easier

- package-lock.json
- packages/get-os-info/package.json
- packages/mongodb-constants/package.json
- packages/mongodb-downloader/package.json
- packages/mongodb-runner/package.json
- packages/monorepo-tools/package.json
- packages/oidc-mock-provider/package.json
- packages/sbom-tools/package.json
Use the same version of typescript as in compass and ([soon](https://github.com/mongodb-js/mongosh/pull/1508)) mongosh.
> chore: use typescript 5.0.4 MONGOSH-1516

- packages/mongodb-runner/src/mongoserver.ts
> fix(mongodb-runner): do not kill mongod process if it already aborted

- packages/mongodb-runner/src/mongocluster.spec.ts
- packages/mongodb-runner/src/mongologreader.ts
> fix(mongodb-runner): allow spawning pre-4.2 mongos processes

- packages/dl-center/package.json
Requirement of https://github.com/mongodb-js/mongosh/pull/1609
> chore(dl-center): bump version to be consistent

- packages/mongodb-constants/src/stage-operators.ts
> feat: add $vectorSearch for 7.0.2+ COMPASS-7064

- packages/mongodb-constants/src/stage-operators.ts
> fix: fix $vectorSearch copy

- package-lock.json
- packages/mongodb-constants/package.json
- packages/mongodb-constants/src/atlas-search-templates.ts
- packages/mongodb-constants/src/index.spec.ts
- packages/mongodb-constants/src/index.ts
> chore: add new atlas search templates COMPASS-7172

- package-lock.json
- packages/mongodb-constants/package.json
- packages/mongodb-constants/src/atlas-search-templates.ts
> chore: reformat and remove dedent COMPASS-7173

- packages/mongodb-constants/src/atlas-search-templates.ts
> chore: fix template for vector embedding

- package-lock.json
- packages/mongodb-runner/package.json
> chore(deps): bump mongodb-connection-string-url to 3.0.0

- packages/signing-utils/src/signing-clients/remote-signing-client.ts
> fix(garasign): download signed rpm

- .github/workflows/bump-packages.yaml
- .github/workflows/update-cidrs.yaml
> chore(ci): fix missing pre-commit

- packages/mongodb-runner/src/cli.ts
This was accidentally removed in 53faa4d27117e1ab3fb6fd015c64df5.
> fix(mongodb-runner): add back arg passing to start command

- packages/oidc-mock-provider/src/index.ts
> feat(oidc-mock-provider): enable skipping the id_token MONGOSH-1669

- packages/monorepo-tools/src/utils/get-conventional-bump.ts
Fixes - https://github.com/mongodb-js/devtools-shared/security/code-scanning/1
> fix(monorepo-tools): fix for suspicious character range in regex

- packages/oidc-mock-provider/src/index.ts
> feat(oidc-mock-provider): allow adding additional keys to issuer metadata

- package-lock.json
- packages/devtools-connect/package.json
- packages/devtools-connect/src/connect.ts
- packages/oidc-mock-provider/src/index.ts
Tests in https://github.com/mongodb-js/mongosh/pull/1868 (which requires this PR)
> feat(devtools-connect): allow applying `useSystemCA` to OIDC IdP MONGOSH-1712

- packages/saslprep/src/generate-code-points.ts
This reverts commit c29f69bfd842e6009861ddf8d2e5542797e83423.
> Revert "chore(saslprep): skip codepoint generation in CI (#188)"

- packages/mongodb-downloader/src/index.ts
This is so that for SSDLC purposes, we fetch not only the `crypt_shared` library for inclusion in Compass and mongosh, but also its version information.
> feat(mongodb-downloader): expose function to get download info along with artifacts

- packages/mongodb-downloader/src/index.ts
Whether the `crypt_shared` tarball contains a `bin` or `lib` folder depends on the platform for which we downloaded the file, not the host platform.
> fix(mongodb-downloader): account for possible `platform: win32` in options

- packages/devtools-connect/src/index.ts
empty commit to trigger another release. when merging last PR, the `!` was at the wrong position and hence it did not trigger the package release correctly.
> feat(devtools-connect)!: add commit to trigger major release

- packages/devtools-connect/src/index.ts
> chore: commit to trigger release

- packages/sbom-tools/src/commands/fetch-codeql-results.ts
By providing the option to either only run the "list all first-party dependencies" step or the "gather CodeQL info for all discovered first-party dependencies" step, we can centralize the CodeQL report generation into a single task for both Compass and mongosh CI. This should reduce our Github API usage and allow us to re-enable runs for patch builds.
> feat(sbom-tools): allow splitting first-party dependency gathering from CodeQL fetches MONGOSH-1804

- packages/query-parser/src/stringify.ts
Jira issue: https://jira.mongodb.org/browse/TOOLS-3466
Related issue: https://github.com/mongo-express/mongo-express/issues/1249
> fix: BinData serialization

- package-lock.json
- packages/mongodb-redact/.depcheckrc
- packages/mongodb-redact/.eslintignore
- packages/mongodb-redact/.eslintrc.js
- packages/mongodb-redact/.mocharc.js
- packages/mongodb-redact/.prettierignore
- packages/mongodb-redact/.prettierrc.json
- packages/mongodb-redact/LICENSE
- packages/mongodb-redact/package.json
- packages/mongodb-redact/src/index.spec.ts
- packages/mongodb-redact/src/index.ts
- packages/mongodb-redact/src/regexes.ts
- packages/mongodb-redact/tsconfig-lint.json
- packages/mongodb-redact/tsconfig.json
Separated into commits for easier review:
> feat(mongodb-redact): move package into monorepo

- package-lock.json
- packages/devtools-connect/package.json
> chore(deps): bump system-ca to 2.x

- packages/mongodb-redact/src/index.spec.ts
- packages/mongodb-redact/src/regexes.ts
- Replace user name in user path
- Do not modify the electron path only hide a user name
- Make all URLs pass the redos checker
> fix(redact): use fast and safe path and email regex MONGOSH-1392

- packages/oidc-mock-provider/src/index.ts
> feat(oidc-mock-provider): allow custom overrides for ID token MONGOSH-1843

- packages/shell-bson-parser/package.json
`bson` is used by `shell-bson-parser` and is a peer dependency. It should be added to dev dependencies to develop and test.
> deps(shell-bson-parser): add bson to dev deps

- package-lock.json
- packages/devtools-proxy-support/package.json
- packages/devtools-proxy-support/src/socks5.ts
- packages/devtools-proxy-support/src/socksv5.d.ts
- packages/devtools-proxy-support/test/helpers.ts
- packages/devtools-proxy-support/test/socksv5.d.ts
PR with changes to the fork was at https://github.com/mongodb-js/socksv5/pull/1
> chore(devtools-proxy-support): use socksv5 fork COMPASS-5472

- .github/workflows/bump-packages.yaml
- .github/workflows/check-test.yaml
- .github/workflows/publish-packages.yaml
- package-lock.json
- packages/node-webpack-startup-snapshot-checker/.depcheckrc
- packages/node-webpack-startup-snapshot-checker/.eslintignore
- packages/node-webpack-startup-snapshot-checker/.eslintrc.js
- packages/node-webpack-startup-snapshot-checker/.mocharc.js
- packages/node-webpack-startup-snapshot-checker/.prettierignore
- packages/node-webpack-startup-snapshot-checker/.prettierrc.json
- packages/node-webpack-startup-snapshot-checker/LICENSE
- packages/node-webpack-startup-snapshot-checker/README.md
- packages/node-webpack-startup-snapshot-checker/bin/node-webpack-startup-snapshot-checker.js
- packages/node-webpack-startup-snapshot-checker/package.json
- packages/node-webpack-startup-snapshot-checker/src/index.spec.ts
- packages/node-webpack-startup-snapshot-checker/src/index.ts
- packages/node-webpack-startup-snapshot-checker/test/fixtures/snapshottable.js
- packages/node-webpack-startup-snapshot-checker/test/fixtures/unsnapshottable.js
- packages/node-webpack-startup-snapshot-checker/tsconfig-lint.json
- packages/node-webpack-startup-snapshot-checker/tsconfig.json
Add a script that tells you whether a module is simple enough or not to be included in a Node.js startup snapshot.
> feat(node-webpack-startup-snapshot-checker): add package

- package-lock.json
- packages/devtools-proxy-support/package.json
- packages/devtools-proxy-support/src/agent.ts
- packages/devtools-proxy-support/src/index.ts
- packages/devtools-proxy-support/src/proxy-agent.ts
- packages/devtools-proxy-support/src/proxy-options-public.ts
- packages/devtools-proxy-support/src/proxy-options.ts
- packages/devtools-proxy-support/src/socks5.spec.ts
- packages/devtools-proxy-support/src/socks5.ts
- packages/devtools-proxy-support/test/helpers.ts
Work around more issues identified while adding testing for proxy support to mongosh.
Admittedly, at this point the original choice to use `proxy-agent` might not seem like the wisest anymore :) We’ll see how receptive their maintainers are to our patches – so far, none of the issues discovered should be fundamentally in conflict with the packages’ design philosophy.
> fix(devtools-proxy-support): work around more issues with proxy-agent

- packages/shell-bson-parser/src/index.spec.ts
- packages/shell-bson-parser/src/scope.ts
> fix(shell-bson-parser): pass non-string arguments of ISODate through to Date MONGOSH-1859

- packages/devtools-proxy-support/src/system-ca.ts
`process.version === 'v' + process.versions.node` 🙃
> fix(devtools-proxy-support): fix node version check

- actions/setup-bot-token/action.yml
Adds the app-slug as output to the setup-app action to mirror https://github.com/actions/create-github-app-token.
> chore: output the github app slug

- .github/workflows/bump-packages.yaml
- .github/workflows/check-test.yaml
- .github/workflows/codeql.yml
- .github/workflows/publish-packages.yaml
- .github/workflows/update-cidrs.yaml
Updates codeql actions and adds actions scanning.
> chore(ci): update codeql workflow

- packages/signing-utils/src/garasign.sh
Something somewhere seems to be silently failing..
> chore: ask jsign for more logging

- package-lock.json
- packages/mongodb-ts-autocomplete/package.json
- packages/ts-autocomplete/package.json
Missed these and now when starting the CLI in https://github.com/mongodb-js/mongosh/pull/2424
```
Error: Cannot find module '@mongodb-js/ts-autocomplete'
Require stack:
- /Users/leroux.bodenstein/mongo/mongosh/node_modules/@mongodb-js/mongodb-ts-autocomplete/dist/autocompleter.js
- /Users/leroux.bodenstein/mongo/mongosh/node_modules/@mongodb-js/mongodb-ts-autocomplete/dist/index.js
- /Users/leroux.bodenstein/mongo/mongosh/packages/cli-repl/lib/mongosh-repl.js
- /Users/leroux.bodenstein/mongo/mongosh/packages/cli-repl/lib/cli-repl.js
- /Users/leroux.bodenstein/mongo/mongosh/packages/cli-repl/lib/run.js
- /Users/leroux.bodenstein/mongo/mongosh/packages/cli-repl/bin/mongosh.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
at Module._load …
```
> chore: some deps are not just dev deps

- package-lock.json
- packages/mongodb-ts-autocomplete/package.json
We're having trouble on mongosh side and trying to see if this helps.
> remove the peer dep

- packages/oidc-mock-provider/src/index.ts
> fix(oidc-mock-provider): allow optional charset in content-type
