packages/bump-monorepo-packages/src/bump-packages.js, packages/bump-monorepo-packages/src/get-conventional-bump.js, packages/bump-monorepo-packages/src/get-conventional-bump.spec.js
Use async functions wherever possible and fix the bump level
determination (`fix:` is semver-patch).
=> chore(bump-monorepo-packages): modernize JS and fix bump calculation

packages/bump-monorepo-packages/README.md, packages/bump-monorepo-packages/src/bump-packages.js, packages/bump-monorepo-packages/src/bump-packages.spec.js, packages/bump-monorepo-packages/src/fixtures/preserve-caret.json, packages/bump-monorepo-packages/src/fixtures/preserve-star.json, packages/bump-monorepo-packages/src/fixtures/preserve-tilde.json, packages/bump-monorepo-packages/src/fixtures/skip-packages-keep-unskipped.json, packages/bump-monorepo-packages/src/fixtures/skip-packages.json
Allows to skip the version bump for some of the packages with `process.env.SKIP_BUMP_PACKAGES`.
NOTE: this is needed in https://github.com/mongodb-js/compass/pull/3309 to avoid updating `mongodb-compass`.
=> feat(bump-monorepo-packages): allow skip packages and preserve ranges

package-lock.json, packages/mongodb-constants/package.json, packages/mongodb-constants/src/stage-operators.spec.ts, packages/mongodb-constants/src/stage-operators.ts
Didn't notice that these existed when moving code from ace-autocompleter
=> chore(mongodb-constants): move tests from ace-autocompleter package

packages/mongodb-constants/src/stage-operators.ts
Instead of showing both Atlas and S3 options at the same time for the `$out` stage in the aggregation builder, which can be confusing to users, show the `$out` to S3 syntax by default. This template is updated to the following snippet, which is outlined in our [docs](https://www.mongodb.com/docs/atlas/data-federation/supported-unsupported/pipeline/out/#syntax) : 
```code:json
/**
* Use any one of the following:
* s3: Parameters to save the data to S3.
* atlas: Parameters to save the data to Atlas. Example:
* {
*   atlas: {
*     db: 'string',
*     coll: 'string',
*     projectId: 'string',
*     clusterName: 'string'
*   }
* }
*/
{
s3: {
bucket: 'string',
region: 'string',
filename: 'string',
format: {
name: 'string',
maxFileSize: 'bytes',
maxRowGroupSize: 'string',
columnCompression: …
```
=> fix: make $out options more clear in aggregation pipeline builder COMPASS-6304

packages/mongodb-constants/src/stage-operators.ts
This small change is related to the work done in the [following PR on mongosh](https://github.com/mongodb-js/mongosh/pull/1412) where we are trying to fix the autocomplete issue for `db.aggregate`. The work done in the mentioned PR requires `db` namespace'd stages that are valid only as first stage to provide suggestions for first stage.
`$documents` which is also a first only stage has been touched to be marked correctly as first stage, in this PR.
=> fix(mongodb-constants): marks "$documents" as first only stage

package-lock.json, packages/mongodb-constants/package.json, packages/mongodb-constants/src/filter.spec.ts, packages/mongodb-constants/src/filter.ts, packages/mongodb-constants/src/index.spec.ts, packages/mongodb-constants/src/index.ts
Extracting this from compass, as we want to use this in vscode too. One difference with compass implementation is that I removed the `prefix` filtering prop as this logic is not used by vscode and codemirror autocompleters, so it's only relevant for ace editor that we are planning to remove anyway
=> feat(mongodb-constants): add filter method

packages/mongodb-constants/src/stage-operators.ts
=> fix(mongodb-constants): remove 'term' operator from $search stage template COMPASS-6817

packages/sbom-tools/README.md, packages/sbom-tools/src/commands/generate-third-party-notices.spec.ts, packages/sbom-tools/src/commands/generate-third-party-notices.ts
We get random "non standard" licenses from `mongosh` dependencies, adding some config to handle those as exceptions.
=> feat(sbom-tools): allow additional licenses and skipping validation for packages

package-lock.json, packages/oidc-mock-provider/bin/oidc-mock-provider.js, packages/oidc-mock-provider/package.json, packages/oidc-mock-provider/src/index.ts
Also adds an option `hostname` to the config options.
=> feat(oidc-mock-provider): add bin script for running mock identity provider server

.depcheckrc, package-lock.json, package.json, packages/bump-monorepo-packages/package.json, packages/bump-monorepo-packages/src/bump-packages.js, packages/bump-monorepo-packages/src/get-packages-in-topological-order.js
=> chore: remove lerna from bump packages

package-lock.json, packages/mongodb-constants/package.json, packages/monorepo-tools/package.json
Bumps the semver version to 7.5.3, addressing the vulnerabilities reported by Snyk.
=> chore: bumps the affected semver installation creating downstream vulnerabilities

package-lock.json, packages/mongodb-downloader/.depcheckrc, packages/mongodb-downloader/.prettierrc.json, packages/mongodb-downloader/package.json, packages/mongodb-runner/.depcheckrc, packages/mongodb-runner/.prettierrc.json, packages/mongodb-runner/package.json
Accidentally added back with mongodb-runner
=> chore: remove references to prettier-config-compass

configs/eslint-config-devtools/common.js, package.json, packages/mongodb-downloader/src/index.ts, packages/mongodb-runner/src/cli.ts, packages/monorepo-tools/src/bump-packages.ts, packages/monorepo-tools/src/depalign.ts, packages/monorepo-tools/src/precommit.ts, packages/monorepo-tools/src/utils/bump-packages.spec.ts, packages/monorepo-tools/src/where.ts, packages/oidc-mock-provider/bin/oidc-mock-provider.js, packages/sbom-tools/src/commands/generate-third-party-notices.ts, packages/sbom-tools/src/commands/generate-vulnerability-report.ts, packages/sbom-tools/src/commands/scan-node-js.ts, packages/sbom-tools/src/jira.ts, packages/sbom-tools/src/production-deps.ts, scripts/src/create-workspace.js
This came out of the mongosh eslint PR.
For consistency there's now a jsRules and jsxRules as well which we might have to remember to spread back in where those rules get extended.
=> chore: disallow eqeqeq and console statements in lint rules MONGOSH-1505

.github/workflows/check-test.yaml, packages/mongodb-runner/package.json, packages/mongodb-runner/src/index.ts, packages/mongodb-runner/src/mongocluster.ts
Instead of only providing the string through a getter, also provide the `ConnectionString` object from `mongodb-connection-string-url`.
This is helpful for consumers which need to modify the connection string before connecting to the spawned cluster.
=> feat(mongodb-runner): add ConnectionString getter to MongoCluster

packages/mongodb-downloader/tsconfig.json, packages/mongodb-runner/tsconfig.json
Since for a few weeks, we will still be supporting Node.js versions that don't support ES2021 TS output in mongosh.
=> fix(mongodb-runner): use es2020 as TS target

package-lock.json, packages/dl-center/.depcheckrc, packages/dl-center/.eslintignore, packages/dl-center/.eslintrc.js, packages/dl-center/.mocharc.js, packages/dl-center/.prettierignore, packages/dl-center/.prettierrc.json, packages/dl-center/LICENSE, packages/dl-center/fixtures/asset.txt, packages/dl-center/fixtures/compass.json, packages/dl-center/package.json, packages/dl-center/src/download-center-config.schema.json, packages/dl-center/src/download-center-config.ts, packages/dl-center/src/download-center.spec.ts, packages/dl-center/src/download-center.ts, packages/dl-center/src/index.ts, packages/dl-center/tsconfig-lint.json, packages/dl-center/tsconfig.json
Allow the dl-center to upload multiple packages for a single platform. For example, being able to specify that Windows contains both .zip and .msi packages.
With this change, we can archive https://github.com/mongodb-js/dl-center
=> feat(dl-center): include download-center in the shared repository and upgrade the dl-center schema MONGOSH-1346

packages/mongodb-constants/src/filter.ts, packages/mongodb-constants/src/index.ts
Just so we can use them easier in Compass
=> chore(mongodb-constants): export types for filter function

packages/mongodb-constants/src/filter.ts, packages/mongodb-constants/src/system-variables.ts
Noticed when trying to do an update of the verison, the types are broken because a non-const value was added to the constants array, this in particular breaks meta type assertion with typescript
=> chore(mongodb-constants): fix constants type

packages/mongodb-constants/src/filter.spec.ts, packages/mongodb-constants/src/filter.ts
The regex that we used to clean up current server version was only picking up a single number from the patch version because of the unnecessary `?` usage. Seems like we had this bug for awhile now, even before we moved all this logic to this package, just never noticed or got reports before, I noticed this only now when testing `$vectorSearch` stage
Also @mcasimir asked to add tests for version as we specify it in constants, added it in the same patch as a drive-by
=> fix(mongodb-constants): fix regexp that picks valid part of semver version

packages/mongodb-constants/src/filter.spec.ts, packages/mongodb-constants/src/filter.ts
While the issue is that the variable name was misspelled, I feel like the root cause is that getting a generic type out of those completion constants is hard and so we had to just manually write a catch-all type for completions. If someone has ideas how to type this package better, please tell!
=> fix(mongodb-constants): fix property name in types and filter function

packages/mongodb-constants/src/stage-operators.spec.ts, packages/mongodb-constants/src/stage-operators.ts
From slack convo https://mongodb.slack.com/archives/GDTJXPHD0/p1698173306955179
Also added a test. We could sort later on, I think is fine here if we have test though, slightly less compute.
=> chore(mongodb-constants): update operators to be alphabetical

packages/saslprep/package.json, packages/saslprep/src/generate-code-points.ts
This PR skips the codepoint generation temporarily to unblock the Github release action from releasing other packages.
https://jira.mongodb.org/browse/COMPASS-7555 is filed to fix codepoint generation.
=> chore(saslprep): skip codepoint generation in CI

package-lock.json, package.json, packages/signing-utils/src/signing-clients/local-signing-client.spec.ts, packages/signing-utils/src/signing-clients/local-signing-client.ts, packages/signing-utils/src/signing-clients/remote-signing-client.spec.ts, packages/signing-utils/src/signing-clients/remote-signing-client.ts, packages/signing-utils/src/ssh-client.ts
This PR does three things
- the local signing client now looks at the exit code of the signing script and rejects if the exit code is non-zero
- moves all SFTP file operations from the remote signing client onto the ssh client (optional change)
- adds @types/ssh2 as a dependency.  this is necessary because currently the compiled TS exports classes which make use of these types.  if we don't specify this as a dependency, `@mongodb-js/signing-utils` fails to compile for users who do not have @types/ssh2 installed.
=> specify ssh2 as dependency

packages/signing-utils/src/garasign.sh, packages/signing-utils/src/signing-clients/index.ts, packages/signing-utils/src/signing-clients/local-signing-client.spec.ts, packages/signing-utils/src/signing-clients/local-signing-client.ts, packages/signing-utils/src/signing-clients/remote-signing-client.spec.ts, packages/signing-utils/src/signing-clients/remote-signing-client.ts, packages/signing-utils/src/utils.ts
In this PR, I added following:
1. Support for `host` in ClientOptions
2. Support for `jsign` options to pass the certificate alias and the timestamp url
3. Update `garasign` to correctly check for signing method
=> fix(signing-utils): fix artifact signing

packages/signing-utils/src/garasign.sh, packages/signing-utils/src/signing-clients/index.ts, packages/signing-utils/src/signing-clients/local-signing-client.spec.ts, packages/signing-utils/src/signing-clients/local-signing-client.ts, packages/signing-utils/src/signing-clients/remote-signing-client.spec.ts, packages/signing-utils/src/signing-clients/remote-signing-client.ts, packages/signing-utils/src/utils.ts
After checking with the build team, we have to use `mongo-authenticode-2021` certificate alias for signing Compass or Mongosh artifacts.
=> chore(signing-utils): remove support for signing options

package-lock.json, packages/signing-utils/package.json, packages/signing-utils/src/signing-clients/remote-signing-client.spec.ts, packages/signing-utils/src/signing-clients/remote-signing-client.ts
Two misc fixes:
- @types/ssh2 is now a prod dependency.  I thought this was already the case, but apparently not.  
- with gpg signing, we don't override the original file when signing remotely.  This isn't necessary because gpg doesn't sign in place, and was causing issues in Mongosh's CI.
Package versions will be bumped automatically according to the PR title:
- The words `BREAKING CHANGE` in the title will cause a **major** bump to all the packages changed in the PR. All dependants will also have a major bump (dependencies, optionalDependencies, peerDependencies) or a patch bump (devDependencies).
- A subject starting with `feat` will cause a **minor** bump to all the packages changed in the PR. All dependants will also have a minor bump (dependencies, optionalDependencies, …
=> chore(signing-utils): add ssh2 types and don't override file with gpg signing

packages/signing-utils/src/garasign.sh, packages/signing-utils/src/signing-clients/index.ts
In order to sign `rpm` package, we need to use `garasign-gpg` image. Its debian and we have to install `rpm` and them import the key in `rpm` manually. In the final step we sign the file.
=> feat(signing): add rpm signing COMPASS-7588

packages/signing-utils/src/garasign.sh
=> chore(garasign): use env file

packages/mongodb-constants/src/expression-operators.ts, packages/mongodb-constants/src/stage-operators.ts
=> chore(mongodb-constants): add 7.1/7.2 aggregation autocomplete updates

packages/mongodb-constants/src/atlas-search-templates.ts, packages/mongodb-constants/src/index.spec.ts
https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-type/
Initially this will be only used in Compass for creating vector search indexes in the ui.
=> feat(mongodb-constants): add vector search index template

packages/oidc-mock-provider/src/index.ts
Actually, what I did before made no sense, because `getTokenPayload` is defined out of the plugin and called from within 🤦 
https://github.com/mongodb-js/oidc-plugin/pull/187/files
=> fix(oidc-mock-provider): move skipIdToken to callback response

packages/query-parser/src/index.spec.ts, packages/query-parser/src/stringify.ts
As part of https://jira.mongodb.org/browse/COMPASS-6980 we need to make Compass not use `stringify` for query parsing so that we can retain multi-spaces in values. We also want to have more flexibility over how we indent those places. This pr adds that flexibility and a deprecated notice on `stringify` so hopefully we can avoid using it in future.
To see a quick example of the bug `stringify` usage causes in Compass, run a query with the following:
```javascript
{
name: 'te    st'
}
```
And then click on it in query history and observe the multiple spaces in `te   st` are replaced by one space.
=> feat(query-parser): allow falsy indentation, default to 2 space in toJSString, deprecate stringify

packages/saslprep/src/node.ts
the recent changes to make saslprep compatible with the browser changed the generated types for Nodejs.  When we tried to consume the latest saslprep in the driver, we get compile errors.
It seems like the combination of `_saslprep.bind` and `Object.assign` erase the type of `saslprep` such that the generated .d.ts file doesn't accurately reflect the types.  
`node.d.ts` before the changes in this PR:
```typescript
declare const saslprep: (args_0: string, args_1?: {
allowUnassigned?: boolean | undefined;
} | undefined) => string;
export = saslprep;
//# sourceMappingURL=node.d.ts.map
```
`node.d.ts` with the changes in this PR:
```typescript
declare function saslprep(input: string, opts?: {
allowUnassigned?: boolean;
}): string;
declare namespace saslprep {
export var saslprep: typeof …
```
=> fix(saslprep): saslprep typing in node.d.ts NODE-5996

.github/workflows/bump-packages.yaml
This is necessary to unblock publishing packages from `main` since we merged 417d35affb2 without further following up on it.
=> fix(saslprep): run code point generation as part of package bumping NODE-6064

packages/mongodb-constants/src/stage-operators.ts
https://jira.mongodb.org/browse/COMPASS-7419
The suggested snippet seemed to have it as the new snippet either in addition to or in place of s3, but our established pattern seems to be to have one option in the snippet and the others documented in the comment so I stuck with that.
=> feat: add azure to the ADL $out description & comment COMPASS-7419

packages/dl-center/src/download-center.spec.ts
This seems to have started resulting in 500 rather than 404 errors (which may be a server-side bug, but nothing that affects our package's functional correctness).
<!--
=> chore(dl-center): relax HTTP status code expectation for invalid config

packages/sbom-tools/src/commands/fetch-codeql-results.ts
Github runs CodeQL on PR merge commits, not PR head commits, so we need a way to identify the CodeQL runs for those merge refs. Do that by accepting a PR number as an environment variable.
=> fix(sbom-tools): allow CodeQL report fetching for PR heads

.github/workflows/check-test.yaml
=> chore(ci): set env var correctly on windows

package-lock.json, packages/devtools-connect/package.json, packages/devtools-connect/src/connect.spec.ts, packages/devtools-connect/src/connect.ts, packages/mongodb-runner/package.json
Missed this option update in https://github.com/mongodb-js/devtools-shared/pull/347 because we didn't bump the driver (and therefore also not its types) in it
=> fix(devtools-connect): bump `mongodb` to latest and fix OIDC option check MONGOSH-1831

packages/oidc-mock-provider/bin/oidc-mock-provider.js, packages/oidc-mock-provider/src/index.ts
`--bind_ip_all` and `bindIpAll` chosen to match the [server's config](https://www.mongodb.com/docs/manual/core/security-mongodb-configuration/).
This helps with docker host networking so that the mongodb server in docker can get to the oidc server you run on the host or another docker container while the issuer remains just localhost.
=> chore(oidc-mock-provider): allow binding to all ips while keeping a specific hostname for the issuer

package-lock.json, packages/mongodb-cloud-info/package.json
Make `gce-ips` a dev dependency to prevent bringing with it a number of extra dependencies to projects that require `mongodb-cloud-info`.
Dependency of https://github.com/mongodb-js/mongosh/pull/2113
=> chore(mongodb-cloud-info): make gce-ips a dev dependency COMPASS-8093

.github/workflows/codeql.yml
Add TypeScript language to CodeQL.
=> build: add TypeScript to CodeQL

packages/devtools-proxy-support/src/agent.spec.ts, packages/devtools-proxy-support/src/agent.ts
This is currently not supported by `https-proxy-agent`. Instead of trying to work around this, let's just keep it simple for now and always stick to the CA option provided to the agent (i.e. typically on the application level).
=> fix(devtools-proxy-support): remove ability to specify per-request CA

packages/devtools-proxy-support/src/agent.spec.ts, packages/devtools-proxy-support/src/agent.ts
=> fix(devtools-proxy-support): add yet another proxy-agent workaround

package-lock.json, packages/mongodb-downloader/package.json
=> chore: update downloader url for the rhel8 fix

packages/devtools-proxy-support/src/socks5.spec.ts, packages/devtools-proxy-support/src/socks5.ts
=> fix(devtools-proxy-agent): properly forward errors for Socks5 requests

packages/devtools-proxy-support/src/logging.ts
Now that SSH forwarding can happen independently from Socks5 proxying, we should adjust the error messages so that they don't accidentally include 'red herring's, like mentioning SSH if the user isn't actually using SSH forwarding.
=> fix(devtools-proxy-support): refer to correct features in error messages

packages/devtools-proxy-support/src/ssh.spec.ts, packages/devtools-proxy-support/src/ssh.ts
This is unfortunately very obvious in retrospect 😞
=> fix(devtools-proxy-support): handle special characters in SSH URL correctly COMPASS-8254

packages/query-parser/package.json
=> fix(mongodb-query-parser): missing `bson` peer dependency

packages/devtools-proxy-support/src/system-ca.spec.ts, packages/devtools-proxy-support/src/system-ca.ts
We ran into more weird issues with CA cert validation failing in unexpected cases (see COMPASS-8322 for more details) affecting users because system CAs are now added to the CA list by default. To work around this particular one we're sorting a list of CAs returned from system store by expiration date to make sure that the ones that will expire sooner or expired already have less of a chance to get picked up from the CA list
=> chore(devtools-proxy-support): push expired certs to the bottom of the system CA list COMPASS-8322

packages/shell-bson-parser/src/index.spec.ts, packages/shell-bson-parser/src/scope.ts
Adds support for the [`valueOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/valueOf) Date method to the `shell-bson-parser` package
=> fix(shell-bson-parser): Support `valueOf` date method

actions/setup-bot-token/action.yml
Creates a trivial wrapper around actions/create-github-app-token to also setup git in addition to getting the token. Since we use the app tokens exclusively in workflows where we want to commit code, this saves us from copy-pasting it in every workflow. It's also provides a centralized place for updating the workflow without having to go and find all usages
=> chore: add a github action for setting up the bot app

.github/workflows/bump-packages.yaml, .github/workflows/check-test.yaml, .github/workflows/codeql.yml, .github/workflows/publish-packages.yaml, .github/workflows/update-cidrs.yaml
This refreshes our ci workflows and switches to using github app tokens instead of the bot user we used to use.
=> chore(ci): use github app instead of bot user

packages/signing-utils/src/garasign.sh
This commit updates the certificate we use to sign to our new one for the next three years. Ideally we would also update this to be parameterized, but given that there are a few projects that depend on this script, I think it's safer to make this update as-is now and decide on templating later.
=> fix(signing-utils): migrate to new Windows signing cert DEVPROD-13200

packages/devtools-connect/src/connect.spec.ts, packages/devtools-connect/src/connect.ts, packages/devtools-connect/src/fast-failure-connect.ts, packages/devtools-connect/src/index.ts, packages/devtools-connect/src/log-hook.ts, packages/devtools-connect/src/types.ts
Recent user reports have made it clear that our attempts to solve TLS errors caused by adding system certificates haven't fully been resolved yet. To address this, we add a generic fallback that attempts to connect a second time without the system certificate store added.
This commit also adds TLS errors to the list of fail-fast errors, i.e. errors which should result in a quick connection end because they are unlikely to be resolved by the Node.js driver attempting to re-connect repeatedly on the level of individual connections. This should avoid situations in which timeouts make the connection attempt take twice as long for TLS errors.
=> fix(devtools-connect): re-try connection in case of TLS errors without system CA MONGOSH-1935

package-lock.json, packages/mongodb-redact/package.json, packages/mongodb-redact/src/index.spec.ts, packages/mongodb-redact/src/index.ts
Just ran into this while writing a test for mongosh that ensures that `shell-api` is really as runtime-independent as we expect.
=> chore(mongodb-redact): remove lodash usage MONGOSH-1975

packages/devtools-connect/src/connect.ts, packages/devtools-connect/src/log-hook.spec.ts, packages/devtools-connect/src/log-hook.ts, packages/devtools-connect/src/types.ts
=> fix(devtools-connect): include DNS resolution time in ConnectDnsResolutionDetail MONGOSH-1998

packages/mongodb-log-writer/src/mongo-log-manager.spec.ts, packages/mongodb-log-writer/src/mongo-log-manager.ts
Adds `retentionGB` which enforces maximal GB of log files which are kept.
=> feat(mongodb-log-writer): add `retentionGB` configuration MONGOSH-1985

packages/mongodb-log-writer/src/mongo-log-manager.spec.ts, packages/mongodb-log-writer/src/mongo-log-manager.ts
This is needed for mongosh to use a `mongosh_` prefix for custom log directories.
Built on top of https://github.com/mongodb-js/devtools-shared/pull/504
=> feat(mongodb-log-writer): add ability to specify a prefix for log files

packages/mongodb-log-writer/package.json
prepack was not updated to match the new compile naming
=> fix(mongodb-log-writer): update prepack to match new naming

.github/workflows/check-test.yaml, package-lock.json, package.json
Currently even if a lerna task fails, lerna still exits with success and so does the CI task.
The cause is the same as https://github.com/mongodb-js/mongosh/pull/1592 with NPM not sending the correct exit code. NPM 9 fixed this so this updates to that.
Example of a task which will actually fail now: https://github.com/mongodb-js/devtools-shared/actions/runs/13263792191/job/37026159185?pr=508
=> fix(ci): use npm@9.x to avoid failing silently

.github/workflows/bump-packages.yaml, .github/workflows/publish-packages.yaml
This is needed in all workflows otherwise it'd break.
=> fix(ci): use npm@9 across across all workflows

.github/workflows/check-test.yaml
`concurrency` settings for the tests workflow currently stop tests if a new commit is merged. This is fine and works as intended but can look a bit weird in main since we usually have a bump commit right after, meaning most commits would end up having cancelled steps and look like CI is in red.
This makes it so the rule doesn't apply on main and we run those tests for every commit.
=> chore(ci): do not cancel in progress tasks on the main branch

packages/mongodb-log-writer/src/mongo-log-manager.spec.ts
We're applying a `writer.end()` to be consistent with other places of properly cleaning the writer after creation as it messes with Windows CI tests.
https://github.com/mongodb-js/devtools-shared/blob/e3b8add78daf222a514c53ecb7a5bb7ad6d1aa78/packages/mongodb-log-writer/src/mongo-log-manager.spec.ts#L571-L573
=> fix(tests): clean up writer to prevent windows test failure

packages/mongodb-log-writer/src/mongo-log-manager.spec.ts, packages/mongodb-log-writer/src/mongo-log-manager.ts
Because in mongosh (and generally), some of our settings like `logRetentionGB` can be undefined while others like `maxLogFileCount` cannot, it's likely users will end up setting multiple of them as `Infinity` if they're looking to unset different things.
Our code skips some checks when some steps when those limits are `undefined` but it won't skip if they're infinite so it can be a performance improvement if we skip those steps if their values are infinite as well.
=> feat(mongodb-log-writer): skip checks for `retentionGB` and `maxLogFileCount` when set to Infinity MONGOSH-2047

packages/get-os-info/src/get-os-info.spec.ts, packages/get-os-info/src/get-os-info.ts
Merging this PR will:
- Refactor the Linux implementation and tests into a parser and something reading the file.
- Add Darwin specific implementation and tests.
=> feat(get-os-info): derive Darwin / MacOS specific OS info COMPASS-9079

packages/dl-center/src/download-center.ts
This commit adjusts download-center.ts to support optional AWS session
tokens. These tokens are necessary if you want to use temporary credentials
for interacting with the download center, which we will in future commits
to mongosh/compass.
=> feat(dl-center): add support for session tokens COMPASS-9149

packages/dl-center/src/download-center.spec.ts, packages/dl-center/src/download-center.ts
This commit adjusts our DownloadCenter's UploadAssetOptions to support taking an optional 'acl' parameter. When we upload an asset to S3, this parameter is used to set the ACL on the put request. If no acl is set, we default to "public-read" to preserve backward compatibility.
=> feat(dl-center): add support for arbitrary acls COMPASS-9237

packages/dl-center/src/download-center.spec.ts, packages/mongodb-cloud-info/src/index.spec.ts, packages/mongodb-cloud-info/src/index.ts
This is to deal with the fact that Atlas has some of their own IP addresses for AWS hosts and that messes up telemetry reporting.
=> fix(mongodb-cloud-info): if the host's IP is not in a cloud's range, check if the CNAME resolves to AWS. COMPASS-8932

packages/mongodb-runner/package.json, packages/native-machine-id/package.json
This is not necessary for native-machine-id but just doing this change to force a release through CI.
=> fix: include type exports for mongodb-runner and native-machine-id

package-lock.json, packages/native-machine-id/package.json, packages/native-machine-id/src/index.ts
- Use explicit paths for requiring as that works better with bundlers
- No need to use `bindings` as the alternative is simpler
- N/A
=> fix(native-machine-id): replace bindings dependency with explicit paths

packages/mongodb-ts-autocomplete/src/autocompleter.spec.ts, packages/mongodb-ts-autocomplete/src/autocompleter.ts, packages/mongodb-ts-autocomplete/src/autocompletion-context.ts
for https://github.com/mongodb-js/mongosh/pull/2464
=> chore: support undefined db/connection

packages/device-id/package.json, packages/devtools-proxy-support/package.json, packages/dl-center/package.json, packages/download-url/package.json, packages/get-os-info/package.json, packages/mongodb-cloud-info/package.json, packages/mongodb-constants/package.json, packages/mongodb-downloader/package.json, packages/mongodb-redact/package.json, packages/mongodb-runner/package.json, packages/mongodb-ts-autocomplete/package.json, packages/mql-typescript/package.json, packages/native-machine-id/package.json, packages/oidc-http-server-pages/package.json, packages/oidc-mock-provider/package.json, packages/query-parser/package.json, packages/sbom-tools/package.json, packages/shell-bson-parser/package.json, packages/signing-utils/package.json, packages/ts-autocomplete/package.json, scripts/src/create-workspace.js
This is a follow-up to https://github.com/mongodb-js/devtools-shared/pull/546 where I didn't properly understand this.
The context of why/where I need this is to be able to use a separate types export from the default one [from mongosh](https://github.com/mongodb-js/mongosh/pull/2478/files). 
The latest error I'm getting there:
```
src/index.ts:428:5 - error TS7016: Could not find a declaration file for module '@mongodb-js/mongodb-ts-autocomplete'. '/Users/leroux.bodenstein/mongo/mongosh/packages/autocomplete/node_modules/@mongodb-js/mongodb-ts-autocomplete/dist/.esm-wrapper.mjs' implicitly has an 'any' type.
There are types at '/Users/leroux.bodenstein/mongo/mongosh/packages/autocomplete/node_modules/@mongodb-js/mongodb-ts-autocomplete/dist/index.d.ts', but this result could not be …
```
=> fix exports in package.json to work with ts's implementation of node16 moduleResolution

packages/devtools-connect/src/connect.spec.ts, packages/devtools-connect/src/connect.ts
https://github.com/mongodb-js/compass/pull/7083
Set the option that makes the driver _not_ run ping on connect.
This removes some errors that could happen:
- Ping tests for authentication because it is a command that runs through the connection pool the connection created must be auth-ed
- The server selected is the primary unless a client-wide read preference was set. This blocks the ping from running until a primary is discovered
This improves some scenarios:
- No longer is a pool (likely the primary) pre populated with one connection when connect returns
- Connect returns sooner than RTT to any particular node since it does not wait on monitoring / server selection 
- Nor does connect wait for a MongoDB handshake RTT in addtion to the ping RTT
Does the error timing matter to downstream …
=> fix(devtools-connect): skip driver ping during connect COMPASS-9536

packages/mongodb-ts-autocomplete/src/autocompleter.spec.ts, packages/ts-autocomplete/src/index.spec.ts, packages/ts-autocomplete/src/index.ts, packages/ts-autocomplete/test/fixtures/code.ts
`db.fo` -> `db["foo.bar"]` rather than `db.foo.bar` so that the result is valid and then if you type on like `db["foo.bar"].fi` it will continue to autocomplete as `db["foo.bar"].find`.
Because `db.foo.bar.fi` won't autocomplete because `db.foo.bar` is invalid if the collection name is `foo.bar`. ie. there is no prop `foo` on `db`.
=> fix: when autocompleting with insertText, use that rather than name

packages/devtools-connect/src/connect.spec.ts, packages/devtools-connect/src/connect.ts, packages/devtools-connect/src/fast-failure-connect.ts, packages/devtools-proxy-support/src/agent.ts, packages/devtools-proxy-support/src/index.ts, packages/devtools-proxy-support/src/logging.ts, packages/devtools-proxy-support/src/proxy-options.ts, packages/devtools-proxy-support/src/system-ca.ts
Restructure our proxy integration logic to:
- Avoid modifying the OIDC options – previously we were assigning to `clientOptions.oidc`, which meant that the `fetch` function created to read the system certificates was also used for the non-system-cert `connect()` call, breaking our fallback mechanism
- Add a test that verifies that the fallback mechanism works both for TLS driver connections and HTTPS OIDC calls.
- Deduplicate the logic for adding CA options to the `DevtoolsProxyOptions` instances.
- Share log info from the OIDC agent instance, if a new one has been created.
- Make sure that TLS errors passed through node-fetch are actually picked up by our "nested error" detection logic (they have a different `toStringTag` defined than regular `Error` instances).
=> fix(devtools-connect): fix TLS error fallback mechanism MONGOSH-2488

packages/devtools-connect/src/index.ts, packages/devtools-connect/src/log-hook.ts, packages/devtools-proxy-support/src/index.ts, packages/devtools-proxy-support/src/logging.ts
Because the OIDC plugin's `MongoLogWriter` class has an optional `debug()` method and the devtools-connect one didn't, we accidentally missed adding this debug method in mongodb-js/mongosh@b340d790ed9c159. Aligning these interfaces should prevent this from happening again in the future.
=> chore(devtools-connect): align `MongoLogWriter` interfaces between packages

packages/mongodb-ns/src/index.spec.ts, packages/mongodb-ns/tsconfig.json
We nearly got it on the first try. Because the test file wasn't named with the "spec" pattern and allowJs was set to true TS was trying to compile index.ts and index.test.js to the same file, and it throws saying it will overwrite. I took the liberty of changing the file both to spec and TS, and unskipped the skipped tests by verifying that all those DB names are valid. 
Can we rerun bump packages / publish with the 3.0.0 version since it never actually released or should I make this a "fix" just to get the 3.0.1 version put in the package.json?
=> chore(mongodb-ns): fix publishing ns package by renaming test file

packages/mongodb-constants/src/stage-operators.ts
For 8.2 support, add `$scoreFusion` stage operator. Docs: [aggregation/scoreFusion](https://www.mongodb.com/docs/manual/reference/operator/aggregation/scoreFusion/)
=> feat(mongodb-constants): add $scoreFusion stage operator COMPASS-9430

packages/mongodb-constants/src/expression-operators.ts
These three operators were added in v8.2.0 (https://jira.mongodb.org/browse/SERVER-104132)
=> feat(mongodb-constants): add vector similarity expression operators COMPASS-9553
